---
- name: Deploying Kubernetes with RKE
  hosts: local
  gather_facts: false
  tasks:
  - name: Import User Variables
    include_vars:
      file: "../config.json"
      name: config
  - name: RKE Kubernetes Installation
    shell:
      cmd: rke up --config ../rke/cluster.yml
  - name: S3 State Bucket - Upload RKE State and Kube config files
    community.aws.s3_sync:
      bucket: "rancher-state-{{ config.cluster_id }}"
      file_root: '../rke/'
      exclude: "*.j2"
      key_prefix: 'rke/'
