---
- name: Provision Higly-Available EC2 and VPC on AWS
  hosts: local
  gather_facts: false
  tasks:
  - name: Import User Variables
    include_vars:
      file: "../config.json"
      name: config
  - name: DynamoDB - Create table for Locking
    community.aws.dynamodb_table:
      name: "rancher-lock-{{ config.cluster_id }}"
      state: present
      hash_key_name: LockID
      hash_key_type: STRING
      read_capacity: 5
      write_capacity: 5
  - name: S3 State Bucket - Create
    amazon.aws.s3_bucket:
      name: "rancher-state-{{ config.cluster_id }}"
      state: present
      region: "{{ config.region }}"
      versioning: yes
      encryption: AES256
      force: yes
  - name: S3 State Bucket - Create IAC directory
    amazon.aws.aws_s3:
      bucket: "rancher-state-{{ config.cluster_id }}"
      object: 'iac/'
      mode: create
  - name: S3 State Bucket - Create RKE directory
    amazon.aws.aws_s3:
      bucket: "rancher-state-{{ config.cluster_id }}"
      object: 'rke/'
      mode: create
  - name: S3 State Bucket - Create SSH directory
    amazon.aws.aws_s3:
      bucket: "rancher-state-{{ config.cluster_id }}"
      object: 'ssh/'
      mode: create
  - name: Deploy Infrastructure
    community.general.terraform:
      project_path: '../terraform/'
      state: present
      force_init: yes
      init_reconfigure: yes
      variables_files: '../config.json'
      backend_config:
        bucket: "rancher-state-{{ config.cluster_id }}"
        key: "iac/terraform.tfstate"
        region: "{{ config.region }}"
        dynamodb_table: "rancher-lock-{{ config.cluster_id }}"
        encrypt: "true"
    register: terraform
  - name: Append bastion to hosts file
    blockinfile:
      path: /etc/ansible/hosts
      block: |
        [bastion]
        "{{ terraform.outputs.bastion.value }}" ansible_ssh_private_key_file="~/.ssh/bastion-{{ config.environment }}}-{{ config.cluster_id }}"
  - name: Register latest RKE supported K8s version
    shell: 
      cmd: rke config --list-version
    register: rke_version
  - name: Generate RKE Configuration - cluster.yml
    template:
      src: '../rke/cluster.j2'
      dest: '../rke/cluster.yml'
    vars:
      nodes: "{{ terraform.outputs.instances_ips.value }}"
      version: "{{ rke_version.stdout }}"
  - meta: refresh_inventory